spring.application.name=concurrencystudy
server.port=8080

spring.datasource.url=jdbc:mysql://119.91.218.124:3306/study
spring.datasource.username=study
spring.datasource.password=study
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.mapper-locations=classpath*:mapper/*.xml

spring.data.redis.host=119.91.218.124
spring.data.redis.port=26739
spring.data.redis.password=yuer
spring.data.redis.database=0
spring.data.redis.timeout=3000

spring.rabbitmq.host=119.91.218.124
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=yuer
spring.rabbitmq.virtual-host=/